import os

OPENAI_API_KEY=os.getenv("OPENAI_API_KEY")
VISION_AGENT_API_KEY=os.getenv("VISION_AGENT_API_KEY")
OPEN_AI_EXTRACTION_MODEL="gpt-4.1-2025-04-14"
OPEN_AI_PARSE_FORMATING_MODEL="gpt-4o-2024-08-06"
ASYNC_OPENAI_RATE_LIMIT=25
ASYNC_OPEN_AI_TIME_PERIOD=60
ASYNC_CONCURRENCY_LIMIT=10
